import Head from 'next/head'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

export default function Home() {

  const [textTitle, setTextTitle] = useState('')
  const [textSubtitle, setTextSubtitle] = useState('')
  const [mode, setMode] = useState('info')
  const [autoClose, setAutoClose] = useState(false)

  return (
    <div>
      <Head>
        <title>Notification System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Notification System</h1>
        <div className={styles.content}>
          <form 
          onSubmit={e => {e.preventDefault()
          }}>
            <div className={styles.autoClose}>
              <input type="checkbox"
              value={autoClose}
              onChange={e => setAutoClose(e.target.checked)} />
              <label>Auto Close</label>
            </div>

            <h5>Choose Mode</h5>
            <select value={mode} onChange={e => setMode(e.target.value)}>
              <option value="info">Info</option>
              <option value="success">Success</option>
              <option value="warning">Warning</option>
              <option value="error">Error</option>
            </select>
            
            <h5>Toast Notification Title</h5>
            <input 
            type="text"
            value={textTitle}
            placeholder='Title of Toast'
            onChange={e => setTextTitle(e.target.value)} />

            <h5>Toast Notification Message</h5>
            <input 
            type="text"
            value={textSubtitle}
            placeholder='Subtitle of Toast'
            onChange={e => setTextSubtitle(e.target.value)} />

            <button>Submit</button>
          </form>
        </div>
      </main>

    </div>
  )
}
