import Head from 'next/head'
import { useRef, useState } from 'react'
import ToastPortal from '../components/ToastPortal'
import styles from '../styles/Home.module.css'

export default function Home() {

  const toastRef = useRef()
  const [textTitle, setTextTitle] = useState('')
  const [textSubtitle, setTextSubtitle] = useState('')
  const [mode, setMode] = useState('info')
  const [autoClose, setAutoClose] = useState(false)

  const addToast = () => {
    toastRef.current.addToasts({ mode:mode, title: textTitle, subTitle: textSubtitle})
  }

  return (
    <div>
      <Head>
        <title>Notification System</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Notification System</h1>
        <div className={styles.content}>
          <form 
            onSubmit={e => {e.preventDefault()
            if(textTitle && textSubtitle) {
              addToast()
              setTextTitle('')
              setTextSubtitle('')
            }
          }}>
            <div className={styles.autoClose}>
              <input type="checkbox"
              value={autoClose}
              onChange={e => setAutoClose(e.target.checked)} />
              <label>Auto Close</label>
            </div>

            <h5>Choose Mode</h5>
            <select value={mode} onChange={e => setMode(e.target.value)}>
              <option value="info">Info</option>
              <option value="success">Success</option>
              <option value="warning">Warning</option>
              <option value="error">Error</option>
            </select>
            
            <h5>Toast Notification Title</h5>
            <input 
            type="text"
            value={textTitle}
            placeholder='Title of Toast'
            onChange={e => setTextTitle(e.target.value)} />

            <h5>Toast Notification Message</h5>
            <input 
            type="text"
            value={textSubtitle}
            placeholder='Subtitle of Toast'
            onChange={e => setTextSubtitle(e.target.value)} />

            <button>Submit</button>
          </form>
        </div>

        <h5>OR</h5>

        <button onClick={() => {
          toastRef.current.addToasts({ mode:'info', title: 'This is a random title', subTitle: 'This is random subtitle'})
        }} className={styles.btn}>Genrate random toast</button>

        <ToastPortal ref={toastRef} autoClose={autoClose} />
      </main>

    </div>
  )
}
